jQuery('document').ready(function(){function footerToBottom(){var browserHeight=$(window).height(),footerOuterHeight=$('footer').outerHeight(true),mainHeightMarginPaddingBorder=$('#main').outerHeight(true)-$('#main').height();$('#main').css({'min-height':browserHeight-footerOuterHeight-mainHeightMarginPaddingBorder-200,});};footerToBottom();$(window).resize(function(){footerToBottom();});function init(){window.addEventListener('scroll',function(e){var distanceY=window.pageYOffset||document.documentElement.scrollTop,shrinkOn=50,header=document.querySelector("header");if(distanceY>shrinkOn){classie.add(header,"smaller");}else{if(classie.has(header,"smaller")){classie.remove(header,"smaller");}}});window.addEventListener('load',function(e){var distanceY=window.pageYOffset||document.documentElement.scrollTop,shrinkOn=100,header=document.querySelector("header");if(distanceY>shrinkOn){classie.add(header,"smaller");}else{if(classie.has(header,"smaller")){classie.remove(header,"smaller");}}});}
window.onload=init();$('.toggle').on('click',function(){$('.menu_button').toggleClass('active');$('.top_phones').hide();});$('.open_top_phones').on('click',function(){$('.top_phones').toggle();$('.navbar-collapse').collapse('hide');$('.menu_button').removeClass('active');$(".navbar-nav li").removeClass('active');});$(document).click(function(e){if($(e.target).closest(".open_top_phones,.top_phones").length)return;$('.top_phones').hide();e.stopPropagation();});$('input[name="phone"]').mask("+7 (999) 999-99-99");jQuery('[data-open-popup-1]').click(function(){jQuery('#win1').fadeIn();return false;})
jQuery('.close_popup').click(function(){jQuery('.inputModal').fadeOut();return false;})
jQuery('[data-open-popup-2]').click(function(){jQuery('#win2').fadeIn();return false;})
jQuery('[data-open-popup-3]').click(function(){jQuery('#win3').fadeIn();return false;})
jQuery('[data-open-popup-4]').click(function(){jQuery('#win4').fadeIn();return false;})
jQuery('[data-open-popup-5]').click(function(){jQuery('#win5').fadeIn();return false;})
$('form').on('submit',function(){jQuery('.succes').fadeIn();jQuery('form').trigger('reset');jQuery('.succes,.inputModal').delay(2000).fadeOut();return false;});jQuery('.close_succes').click(function(){$('.succes,.inputModal').hide();return false;})
$(document).click(function(e){if($(e.target).closest("#popup_1").length)return;$('#win1,#succes_1').fadeOut();e.stopPropagation();});$(document).click(function(e){if($(e.target).closest("#popup_2").length)return;$('#win2,#succes_2').fadeOut();e.stopPropagation();});$(document).click(function(e){if($(e.target).closest("#popup_3").length)return;$('#win3,#succes_3').fadeOut();e.stopPropagation();});$(document).click(function(e){if($(e.target).closest("#popup_4").length)return;$('#win4,#succes_4').fadeOut();e.stopPropagation();});$(document).click(function(e){if($(e.target).closest("#popup_5").length)return;$('#win5,#succes_5').fadeOut();e.stopPropagation();});function hren(){$(this).parents('li').find(".sub_menu").slideToggle("slow");return false;}
var bb=false;if($(window).width()<=993){if(!bb){$(".has_child>a").bind("click",hren);bb=true;}}else{if(bb){$(".has_child>a").unbind("click",hren);bb=false;}}
$(window).on('resize',function(){if($(window).width()<=993){if(!bb){$(".has_child>a").bind("click",hren);bb=true;}}else{if(bb){$(".has_child>a").unbind("click",hren);bb=false;}}});$(".navbar-nav li a.nav-link").click(function(){var selected=$(this).attr('href');$.scrollTo(selected,700,{offset:function(){return{top:-129};}});$('.navbar-collapse').collapse('hide');$('.menu_button').removeClass('active');$(".navbar-nav li").removeClass('active');$(this).parents(".navbar-nav li").addClass('active');return false;});$(".tptable_toright_nav  a").click(function(){var selected2=$(this).attr('href');$.scrollTo(selected2,700,{offset:function(){return{top:-129};}});$('.navbar-collapse').collapse('hide');$('.menu_button').removeClass('active');$(".navbar-nav li").removeClass('active');return false;});var slider=$('.event_slider').slick({dots:true,arrows:false,speed:800,slidesToShow:1,slidesToScroll:1,autoplay:true,autoplaySpeed:4000,responsive:[{breakpoint:992,settings:{adaptiveHeight:true,autoplay:false}}]});total=slider.slick("getSlick").slideCount;currentSlide=$('.event_slider').slick('slickCurrentSlide');slide=currentSlide+1;if(total>1){$(".sl-count__current").text('0'+slide);$('.sl-count__total').text('0'+total);}
$(".event_slider").on('afterChange',function(event,slick,currentSlide,nextSlide){var currentSl=currentSlide+1;$(".sl-count__current").text('0'+currentSl);});function dotsToleft(){var dots_w=$(".event_slider .slick-dots").width();$('.event_slider .slick-dots').css({'margin-left':-dots_w});};dotsToleft();$(window).resize(function(){dotsToleft();});$(".partners .show_more_p").click(function(){$(this).parents(".partners_body").toggleClass("open");});jQuery('.open_txt').on('click',function(){jQuery(this).parents('.txt_post').find(".txt_hidden").toggle("fast",function(){return false;});jQuery(this).parents('.txt_post').find('.open_txt').toggleClass('open');if(jQuery(this).parents('.txt_post').find(".open_txt").hasClass('open')){jQuery(this).parents('.txt_post').find(".open.open_txt").text('Скрыть...');}else{jQuery(this).parents('.txt_post').find(".open_txt").text('Читать целиком');}
return false;});$(".faq_content .show_more_p").click(function(){$(this).parents(".faq_content").toggleClass("open");});$(window).scroll(function(){if($(this).scrollTop()!=0){$('#toTop').fadeIn();}else{$('#toTop').fadeOut();}});$('#toTop').click(function(){$('body,html').animate({scrollTop:0},800);});var $range_1=$("#range_slider_1");$range_1.ionRangeSlider({skin:"round",type:"single",min:3,max:8,from:3,grid:true,grid_snap:true,postfix:" час."});if(from=3){$('#real_price_1').text(5900);$('#old_price_1').text(6400);}
$('#old_price_1').css({'opacity':"1"});var old_pr_txt_1=$('#old_price_1').text();if(old_pr_txt_1==0){$('#old_price_1').css({'opacity':"0"});}else{$('#old_price_1').css({'opacity':"1"});}
$range_1.on("change",function(){var $inp=$(this);from=$inp.prop("value");if(from==3){$('#real_price_1').text(5900);$('#old_price_1').text(6400);}
if(from==4){$('#real_price_1').text(6900);$('#old_price_1').text(7700);}
if(from==5){$('#real_price_1').text(8200);$('#old_price_1').text(0);}
if(from==6){$('#real_price_1').text(9300);$('#old_price_1').text(0);}
if(from==7){$('#real_price_1').text(10500);$('#old_price_1').text(0);}
if(from==8){$('#real_price_1').text(11700);$('#old_price_1').text(0);}
$('#old_price_1').css({'opacity':"1"});var old_pr_txt_1=$('#old_price_1').text();if(old_pr_txt_1==0){$('#old_price_1').css({'opacity':"0"});}else{$('#old_price_1').css({'opacity':"1"});}});var $range_2=$("#range_slider_2");$range_2.ionRangeSlider({skin:"round",type:"single",min:3,max:8,from:3,grid:true,grid_snap:true,postfix:" час."});if(from=3){$('#real_price_2').text(7500);$('#old_price_2').text(7800);}
$('#old_price_2').css({'opacity':"2"});var old_pr_txt_2=$('#old_price_2').text();if(old_pr_txt_2==0){$('#old_price_2').css({'opacity':"0"});}else{$('#old_price_2').css({'opacity':"1"});}
$range_2.on("change",function(){var $inp=$(this);from=$inp.prop("value");if(from==3){$('#real_price_2').text(6900);$('#old_price_2').text(7800);}
if(from==4){$('#real_price_2').text(7900);$('#old_price_2').text(9000);}
if(from==5){$('#real_price_2').text(9600);$('#old_price_2').text(0);}
if(from==6){$('#real_price_2').text(10900);$('#old_price_2').text(0);}
if(from==7){$('#real_price_2').text(11900);$('#old_price_2').text(0);}
if(from==8){$('#real_price_2').text(13500);$('#old_price_2').text(0);}
$('#old_price_2').css({'opacity':"2"});var old_pr_txt_2=$('#old_price_2').text();if(old_pr_txt_2==0){$('#old_price_2').css({'opacity':"0"});}else{$('#old_price_2').css({'opacity':"1"});}});var $range_3=$("#range_slider_3");$range_3.ionRangeSlider({skin:"round",type:"single",min:3,max:8,from:3,grid:true,grid_snap:true,postfix:" час."});if(from=3){$('#real_price_3').text(9900);$('#old_price_3').text(10700);}
$('#old_price_3').css({'opacity':"2"});var old_pr_txt_3=$('#old_price_3').text();if(old_pr_txt_3==0){$('#old_price_3').css({'opacity':"0"});}else{$('#old_price_3').css({'opacity':"1"});}
$range_3.on("change",function(){var $inp=$(this);from=$inp.prop("value");if(from==3){$('#real_price_3').text(9900);$('#old_price_3').text(10700);}
if(from==4){$('#real_price_3').text(11900);$('#old_price_3').text(12800);}
if(from==5){$('#real_price_3').text(13900);$('#old_price_3').text(0);}
if(from==6){$('#real_price_3').text(15600);$('#old_price_3').text(0);}
if(from==7){$('#real_price_3').text(16900);$('#old_price_3').text(0);}
if(from==8){$('#real_price_3').text(19000);$('#old_price_3').text(0);}
$('#old_price_3').css({'opacity':"2"});var old_pr_txt_3=$('#old_price_3').text();if(old_pr_txt_3==0){$('#old_price_3').css({'opacity':"0"});}else{$('#old_price_3').css({'opacity':"1"});}});var $range_4=$("#range_slider_4");$range_4.ionRangeSlider({skin:"round",type:"single",min:3,max:8,from:3,grid:true,grid_snap:true,postfix:" час."});if(from=3){$('#real_price_4').text(12900);$('#old_price_4').text(14200);}
$('#old_price_4').css({'opacity':"2"});var old_pr_txt_4=$('#old_price_4').text();if(old_pr_txt_4==0){$('#old_price_4').css({'opacity':"0"});}else{$('#old_price_4').css({'opacity':"1"});}
$range_4.on("change",function(){var $inp=$(this);from=$inp.prop("value");if(from==3){$('#real_price_4').text(12900);$('#old_price_4').text(14200);}
if(from==4){$('#real_price_4').text(15700);$('#old_price_4').text(17700);}
if(from==5){$('#real_price_4').text(18400);$('#old_price_4').text(0);}
if(from==6){$('#real_price_4').text(20600);$('#old_price_4').text(0);}
if(from==7){$('#real_price_4').text(22400);$('#old_price_4').text(0);}
if(from==8){$('#real_price_4').text(25100);$('#old_price_4').text(0);}
$('#old_price_4').css({'opacity':"2"});var old_pr_txt_4=$('#old_price_4').text();if(old_pr_txt_4==0){$('#old_price_4').css({'opacity':"0"});}else{$('#old_price_4').css({'opacity':"1"});}});var $range_5=$("#range_slider_5");$range_5.ionRangeSlider({skin:"round",type:"single",min:3,max:8,from:3,grid:true,grid_snap:true,postfix:" час."});if(from=3){$('#real_price_5').text(15900);$('#old_price_5').text(17100);}
$('#old_price_5').css({'opacity':"2"});var old_pr_txt_5=$('#old_price_5').text();if(old_pr_txt_5==0){$('#old_price_5').css({'opacity':"0"});}else{$('#old_price_5').css({'opacity':"1"});}
$range_5.on("change",function(){var $inp=$(this);from=$inp.prop("value");if(from==3){$('#real_price_5').text(15900);$('#old_price_5').text(17100);}
if(from==4){$('#real_price_5').text(18900);$('#old_price_5').text(19900);}
if(from==5){$('#real_price_5').text(22100);$('#old_price_5').text(0);}
if(from==6){$('#real_price_5').text(24800);$('#old_price_5').text(0);}
if(from==7){$('#real_price_5').text(27000);$('#old_price_5').text(0);}
if(from==8){$('#real_price_5').text(29900);$('#old_price_5').text(0);}
$('#old_price_5').css({'opacity':"2"});var old_pr_txt_5=$('#old_price_5').text();if(old_pr_txt_5==0){$('#old_price_5').css({'opacity':"0"});}else{$('#old_price_5').css({'opacity':"1"});}});var $range_6=$("#range_slider_6");$range_6.ionRangeSlider({skin:"round",type:"single",min:3,max:8,from:3,grid:true,grid_snap:true,postfix:" час."});if(from=3){$('#real_price_6').text(22000);$('#old_price_6').text(0);}
$('#old_price_6').css({'opacity':"2"});var old_pr_txt_6=$('#old_price_6').text();if(old_pr_txt_6==0){$('#old_price_6').css({'opacity':"0"});}else{$('#old_price_6').css({'opacity':"1"});}
$range_6.on("change",function(){var $inp=$(this);from=$inp.prop("value");if(from==3){$('#real_price_6').text(24200);$('#old_price_6').text(0);}
if(from==4){$('#real_price_6').text(28800);$('#old_price_6').text(0);}
if(from==5){$('#real_price_6').text(33800);$('#old_price_6').text(0);}
if(from==6){$('#real_price_6').text(38000);$('#old_price_6').text(0);}
if(from==7){$('#real_price_6').text(42500);$('#old_price_6').text(0);}
if(from==8){$('#real_price_6').text(46600);$('#old_price_6').text(0);}
$('#old_price_6').css({'opacity':"2"});var old_pr_txt_6=$('#old_price_6').text();if(old_pr_txt_6==0){$('#old_price_6').css({'opacity':"0"});}else{$('#old_price_6').css({'opacity':"1"});}});jQuery('.load_more').on('click',function(){jQuery(this).parents('.portfolio_body').find(".hidden").slideToggle("150",function(){return false;});jQuery(this).parents('.portfolio_body').find('.load_more').toggleClass('open');if(jQuery(this).parents('.portfolio_body').find(".load_more").hasClass('open')){jQuery(this).parents('.portfolio_body').find(".open.load_more").text('СКРЫТЬ');}else{jQuery(this).parents('.portfolio_body').find(".load_more").text('Загрузить еще');}
return false;});jQuery('.more_photos').on('click',function(){jQuery(this).parents('.gallery_body').find(".hidden").slideToggle("150",function(){return false;});jQuery(this).parents('.gallery_body').find('.load_more').toggleClass('open');return false;});$('.menu_slider').slick({prevArrow:'<div class="prev"><span class="flaticon-down-arrow"></span></div>',nextArrow:'<div class="next"><span class="flaticon-down-arrow"></span></div>',dots:false,arrows:true,speed:800,slidesToShow:1,slidesToScroll:1,autoplay:true,autoplaySpeed:4000,responsive:[{breakpoint:992,settings:{}}]});$(".mixt_greed .show_more_p").click(function(){$(this).parents(".mixt_greed").toggleClass("open");});$('[data-fancybox="gallery2"]').fancybox({});});